
version: '3'

services:
  app:
    container_name: subtitle-app
    build: '.'
    volumes:
      - .:/home/pixote/Gui/crawler
      - /home/pixote/Gui/crawler/node_modules
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    
  mongo:
    container_name: subtitle-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - /home/pixote/Gui/crawler:/data/db
    networks:
      - mongo-compose-network

networks: 
  mongo-compose-network:
    driver: bridge