
version: '3'

services:
    
  mongo:
    container_name: subtitle-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: subtitle-app
    depends_on:
      - mongo

volumes:
  mongodb_data_container:

